### ISSUE TITLE
User can search for a type of pet in their area

### ISSUE THREAD

**Issue by ChristinaL24** [ChristinaL24/Paws-N-Pals#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a type of pet in their area.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able match with a specific pet after inputting the values for the location and selecting the type of animal.

## 🖼️ Wireframes
> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

**Figma:**
https://www.figma.com/file/apnDFsBloZGQXILmwmaOFk/Christina-Le---Final-Project?node-id=0%3A1

**Mobile:**

![Screen Shot 2022-04-14 at 11 36 29 PM](https://user-images.githubusercontent.com/97194651/163531732-8fbfb74e-e5f7-4140-9b38-16469bdd6eed.png)

**Desktop**:

![Screen Shot 2022-04-13 at 1 14 54 PM](https://user-images.githubusercontent.com/97194651/163263014-7d2973cb-d83f-44ff-ac4b-223a114464c9.png)
![Screen Shot 2022-04-13 at 1 15 01 PM](https://user-images.githubusercontent.com/97194651/163263021-ffa8e7c5-cf22-44f0-9fbf-600cc9ee9174.png)
![Screen Shot 2022-04-13 at 1 15 17 PM](https://user-images.githubusercontent.com/97194651/163263028-effb72eb-acf3-46a6-aaba-3c82b7b7476c.png)
![Screen Shot 2022-04-14 at 11 37 56 PM](https://user-images.githubusercontent.com/97194651/163531838-18577911-a846-4e60-9b1c-62ac5a12052d.png)
![Screen Shot 2022-04-13 at 1 15 36 PM](https://user-images.githubusercontent.com/97194651/163263041-e08545a8-95cd-4fdd-a41a-a65723098f20.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Make a copy of the .env.example file and name it .env
- [x] Install the PetFinder npm package
- [x] Install other packages with npm install
- [x] Within index.js:
  - [x] Call the require function on '@petfinder/petfinder-js' and assign its value to a variable
  - [x] Call the client method on the apiKey and secret object and assign its value to a variable
  - [x] Query the API using the PetFinder npm package using the location and type
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create the home page component, within it: 
  - [x] Create the component for the navigation bar
  - [x] Create a form component that contains a search bar and a drop down menu
  - [x] Create a button that will submit the client's preferences to the server
- [x] Create a page to display the matched results after the client clicks next
  - [x] Implement hash routing from the search page(home page) to the matches page(result page)
- [x] Populate the matches page with the client's input values
- [x] Ensure that the home icon in the nav bar takes the user back to the search home page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all console logs.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
