### ISSUE TITLE
User can sign up for an account 

### ISSUE THREAD

**Issue by ChristinaL24** [ChristinaL24/paws-n-pals#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can sign up for an account with Paws N Pals.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will have the option to create an account on Paws N Pals. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Figma:
https://www.figma.com/file/apnDFsBloZGQXILmwmaOFk/Christina-Le---Final-Project?node-id=0%3A1

**Mobile:**
![Screen Shot 2022-05-05 at 4 43 23 PM](https://user-images.githubusercontent.com/97194651/167044259-631550f9-91fb-4216-a233-594d91b52cad.png)

**Desktop:**
![Screen Shot 2022-05-05 at 4 43 11 PM](https://user-images.githubusercontent.com/97194651/167044265-4aa65fc7-20d4-487e-b1f3-2a2db33d8b0f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create a new table for the users
- [x] Update `data.sql` to have user info inserted into users table

### ☁️ Server

- [x] Update `server/index.js` to respond to client's request to sign up
- [x] Ensure that user's credential is successfully inserted into database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for the sign up page
- [x] Update hash routing for sign up component 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
