### ISSUE TITLE
User can 'heart'/save animals they matched with

### ISSUE THREAD

**Issue by ChristinaL24** [ChristinaL24/Paws-N-Pals#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to save the pet they get matched with.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to save the pet that they match with by selecting the heart button. The page will present a new match after they hit the 'heart' button.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Figma: https://www.figma.com/file/apnDFsBloZGQXILmwmaOFk/Christina-Le---Final-Project?node-id=1%3A4

**Mobile:
![Screen Shot 2022-04-17 at 12 47 48 AM](https://user-images.githubusercontent.com/97194651/163705603-6fa6de0f-d5c0-474d-865b-79048f8a3f7f.png)

Desktop:**
![Screen Shot 2022-04-17 at 12 50 09 AM](https://user-images.githubusercontent.com/97194651/163705658-e6283f6c-4449-4299-9046-a4c24a7920a7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Ensure that PostgreSQL is running and online 
- [x] Use createdb to create a new database named pets
- [x] Use npm run db:import to set up schema.sql
- [x] Verify that the database was created 
- [x] Start pgweb by running pgweb --db=pets
- [x] Ensure that the saved pet is in the favorites table after it has been inserted

### ☁️ Server

- [x] Update `server/index.js` to respond user's save request 
- [x] Use PostgreSQL to `insert` the saved pet into the favorites table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a saved button so that the user can save their matched pets
- [x] Listen for the onClick event on the 'heart' button 
  - [x] Ensure that a post request is being sent to the server
  - [x] Ensure that petId gets saved into the database when user selects save
- [x] Ensure that page refreshes to new pet after user hits save 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Remove all console logs.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
