### ISSUE TITLE
Users can 'x'(unmatch) the animals that they are not interested in

### ISSUE THREAD

**Issue by ChristinaL24** [ChristinaL24/Paws-N-Pals#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can "unmatch"  with animals they are not interested in
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can select the 'x' button to 'unmatch' with the animals that they are not interested in. The page will present a new match after they hit the 'x' button.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Figma: https://www.figma.com/file/apnDFsBloZGQXILmwmaOFk/Christina-Le---Final-Project?node-id=1%3A4
## ✅ Task List

**Mobile:

![Screen Shot 2022-04-18 at 3 36 52 PM](https://user-images.githubusercontent.com/97194651/163888268-bb46e949-f5f4-48e4-83d4-0030679e789c.png)

Desktop:**

![Screen Shot 2022-04-17 at 11 55 19 AM](https://user-images.githubusercontent.com/97194651/163728569-8136a671-cadd-482e-a557-e50314808454.png)

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Add a button that will handle the "unmatch" functionality 
- [x] Listen for the onClick event on the 'x' button
- [x] Ensure that the page refreshes after the user selects the 'x' button and a new animal is displayed

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
