### ISSUE TITLE
User can view saved matches list

### ISSUE THREAD

**Issue by ChristinaL24** [ChristinaL24/Paws-N-Pals#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view saved matches list.

## 📐 Functionality

Users will be able to access all of their saved matches in the matches tab of the drawer component.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Figma: https://www.figma.com/file/apnDFsBloZGQXILmwmaOFk/Christina-Le---Final-Project?node-id=1%3A4

**Mobile:
![Screen Shot 2022-04-18 at 11 06 09 PM](https://user-images.githubusercontent.com/97194651/163936970-4fa01eb1-af21-48c9-b335-ca5b686620a2.png)

Desktop:**

![Screen Shot 2022-04-18 at 11 05 04 PM](https://user-images.githubusercontent.com/97194651/163936903-15a400e4-d5e0-47ea-a7e2-d16a65da8c5c.png)

![Screen Shot 2022-04-18 at 3 40 57 PM](https://user-images.githubusercontent.com/97194651/163889140-40be6768-9fe7-4f7c-a88b-066d219229d9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to get all the saved animals from the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add a drawer button on the navbar
- [x] Add a drawer component to the navbar
- [x] Within the drawer component:
  - [x] Create a tab named home and ensure that it takes user back to home page when clicked
  - [x] Create a tab named Matches and ensure that it takes the user to the saved matches page when clicked
- [x] Create a page that will display all the saved matches 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
