### ISSUE TITLE
User can view details of each pal

### ISSUE THREAD

**Issue by ChristinaL24** [ChristinaL24/Paws-N-Pals#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the details of each saved matches.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to view a more in-depth description of each pal that they matched within the saved matches page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

**Figma**:
https://www.figma.com/file/apnDFsBloZGQXILmwmaOFk/Christina-Le---Final-Project?node-id=0%3A1

**Mobile:
![Screen Shot 2022-04-21 at 10 20 15 PM](https://user-images.githubusercontent.com/97194651/164609007-b773c7b2-8d3b-417c-8661-183dad33af4b.png)

Desktop:**
![Screen Shot 2022-04-21 at 10 26 11 PM](https://user-images.githubusercontent.com/97194651/164609016-2d5846fb-286d-49b6-90b7-42a7d16c0e09.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to `GET` the details of the selected pal with the petId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a new page that will display the details of the pal when clicked
- [x] Update app.jsx to include the correct hash route to the view details page
- [x] Add a button that will return the user back to the saved-matches
- [x] Ensure that when the user clicks on a saved pal, the correct pal populates the details page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
