### ISSUE TITLE
User can delete pals they are no longer interested in

### ISSUE THREAD

**Issue by ChristinaL24** [ChristinaL24/Paws-N-Pals#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to delete a saved pal from their saved matches page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By clicking the heart icon on the pal's image, users will be able to 'un-match'/delete with the selected pal. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

**Figma:**
https://www.figma.com/file/apnDFsBloZGQXILmwmaOFk/Christina-Le---Final-Project?node-id=0%3A1

**Mobile:
![Screen Shot 2022-04-22 at 12 40 16 PM](https://user-images.githubusercontent.com/97194651/164783215-86a9f345-c950-4faa-9c96-c33d818bb6eb.png)

Desktop:**
![Screen Shot 2022-04-22 at 12 41 30 PM](https://user-images.githubusercontent.com/97194651/164783234-b81f7663-bef9-4f9d-9394-467b48a80bab.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Check database to ensure that correct pet is being deleted 

### ☁️ Server

- [x] Update `server/index.js` to include an app.delete
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add a heart button to the pet's image
- [x] Ensure that the saved pal gets deleted on the user's click
  - [x] Ensure that the saved matches page reflects the changes after a pal gets deleted

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
