### ISSUE TITLE
User can view the location of the pal on google maps

### ISSUE THREAD

**Issue by ChristinaL24** [ChristinaL24/Paws-N-Pals#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to view where a pal is located through google maps.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Within the pal's details page, users will be able to view a google map of where the pal is located.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

**Figma:**
https://www.figma.com/file/apnDFsBloZGQXILmwmaOFk/Christina-Le---Final-Project?node-id=0%3A1

**Mobile:
![Screen Shot 2022-04-24 at 2 52 57 PM](https://user-images.githubusercontent.com/97194651/164998203-4bea28bd-848c-41f1-a727-f7bb74891c1b.png)

Desktop:**
![Screen Shot 2022-04-24 at 2 51 51 PM](https://user-images.githubusercontent.com/97194651/164998166-af127ed2-5dee-4ea8-974b-84ded55d33ab.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Install the react google map package at [click here](https://www.npmjs.com/package/@react-google-maps/api)]
- [x] Install google geocoding package [click here](https://www.npmjs.com/package/react-geocode)
  - [x] Ensure that package is in package.json
- [x] Create a component for google maps display
- [x] Ensure that the correct long and lat is being passed into the google map component
- [x] Ensure that the google map component matches the wireframe of both the desktop and mobile view

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
